### ISSUE TITLE
New release planned ?

### ISSUE THREAD

**Issue by obazoud** [sensu-plugins/sensu-plugins-docker#14]
Is a new release planned any time soon for this plugin ? That last release was in August.

**Comment by eheydrick** [comment]
Yes, I'd like https://github.com/sensu-plugins/sensu-plugins-docker/pull/13 merged and then we can cut a new release.

**Comment by analytically** [comment]
@eheydrick we should apply the changes in #13 to the other checks/metrics too, and release a next major version.

**Comment by kelcecil** [comment]
@eheydrick @analytically: I can apply the desired changes to the other checks and submit PRs for them if it'll help speed the process along. Are you referring to removing the protocol argument from #13? I can just hit #15 while I'm at it.

**Comment by analytically** [comment]
@kelcecil that'd be great! We'll release this as a new major version then.

**Comment by kelcecil** [comment]
@analytically Good deal. I've got some down time coming later in the week, so I'll be on it soon.

**Comment by kelcecil** [comment]
@analytically @mattyjones Is there a preference on how checks talk to Docker? Each of these checks each communicate differently, and I'm trying to make it consistent. I'm currently just making an HTTP call to either the TCP endpoint or through the Unix socket and not using any gems outside of what's in Ruby's standard libraries to do so. Is that okay, or would use of a gem (docker-api) be preferred?

**Comment by eheydrick** [comment]
I have no preference as long as it's consistent.

**Comment by kelcecil** [comment]
I nearly have the regular checks running. The Graphite metrics stuff will take longer as I have zero experience with those.

**Comment by eheydrick** [comment]
@kelcecil how's the rework going? I'd like to include it in the next release. Holler if you need a hand with anything.

**Comment by bzang** [comment]
Any word on this? Would love to see a release come out soon. The Log reader piece would be especially useful.

**Comment by lauraglasu** [comment]
+1

**Comment by kelcecil** [comment]
My changes for this were merged by @sstarcher a week or so ago. I think
we're just waiting on the gem to go out.

**Comment by chuckwired** [comment]
:+1:

**Comment by eheydrick** [comment]
At last 1.0.0 has been released to rubygems! Thanks everyone. Please test and provide feedback.
