### ISSUE TITLE
Make unix://var/run/docker.sock default (or fall back?) interface

### ISSUE THREAD

**Issue by soichih** [sensu-plugins/sensu-plugins-docker#15]
According to docker

```
By default the Docker daemon listens on unix:///var/run/docker.sock
```

Currently, I have to do following to run metrics-docker-stats

```
/opt/sensu/embedded/bin/ruby ./metrics-docker-stats.rb -H /var/run/docker.sock -p unix
```

I think -p unix -H /var/run/docker.sock should be the default interface method for these plugin - or make it automatically fall back to it.

By the way, metrics-docker-container.rb doesn't even support -p unix. Is it to possible to support it?

**Comment by thebenwaters** [comment]
+1

**Comment by eheydrick** [comment]
Version 1.0.0 just released moves to connecting to the socket. Can you test and provide feedback.

**Comment by thebenwaters** [comment]
Yes will test!
