### ISSUE TITLE
metrics-docker-stats.rb does not execute correctly when /containers/json has multiple chunks

### ISSUE THREAD

**Issue by tata2000** [sensu-plugins/sensu-plugins-docker#18]
In this case only first chunk is read and JSON.parse(chunk) fails 
(because the JSON is incomplete)

**Comment by bennibu** [comment]
+1

I guess this would be an easy change in https://github.com/sensu-plugins/sensu-plugins-docker/blob/master/bin/metrics-docker-stats.rb#L120. The `read_body` method could be used without the block. Than you don't have to deal with chunks. See http://ruby-doc.org/stdlib-2.1.1/libdoc/net/http/rdoc/Net/HTTPResponse.html#method-i-read_body

**Comment by majormoses** [comment]
is this still an issue after the pr was merged?

**Comment by majormoses** [comment]
closing as it seems like it was fixed: https://github.com/sensu-plugins/sensu-plugins-docker/issues/42
