### ISSUE TITLE
check-container-logs.rb missing from sensu-install

### ISSUE THREAD

**Issue by thebenwaters** [sensu-plugins/sensu-plugins-docker#26]
<img width="1063" alt="screen shot 2016-05-19 at 18 28 41" src="https://cloud.githubusercontent.com/assets/696445/15399246/91d5e964-1def-11e6-86a7-c243c6173fa1.png">

Is missing

**Comment by eheydrick** [comment]
Yes, hoping to cut a new release soon.

**Comment by eheydrick** [comment]
1.0.0 is out on rubygems now.

**Comment by thebenwaters** [comment]
Is there an easy way to upgrade? @eheydrick

**Comment by eheydrick** [comment]
`sudo /opt/sensu/embedded/bin/gem update sensu-plugins-docker --no-rdoc --no-ri` will update to the latest version.
