### ISSUE TITLE
Issue with using check-docker-container.rb

### ISSUE THREAD

**Issue by lazam** [sensu-plugins/sensu-plugins-docker#37]
I tried using multiple ways to use this plugin "check-docker-container.rb" but I'm having an error. Below are the syntax that I've tried.

```
check-docker-container.rb -h 127.0.0.1:/var/run/docker.sock -c 6
check-docker-container.rb -h /var/run/docker.sock -c 6
check-docker-container.rb -h 127.0.0.1 -c 6
check-docker-container.rb /var/run/docker.sock -c 6

```
Here is the error:

```CheckDockerContainers WARNING: Error: #<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:2375 (Connection refused - connect(2) for "127.0.0.1" port 2375)>```

We're running docker with multiple ports so the best way is to check the /var/run/docker.sock. I'm not sure if I'm doing the right thing since I'm new to Sensu.

**Comment by eheydrick** [comment]
You want to do `check-docker-container.rb -h /var/run/docker.sock` to connect to the docker socket. You will need to give the user executing the check access to the docker socket. This could be accomplished using sudo e.g. `sudo -u sensu -g docker check-docker-container.rb -h /var/run/docker.sock`

**Comment by lazam** [comment]
It worked. Thanks for the help!
