### ISSUE TITLE
Update Sensu Plugin to 1.3 or higher

### ISSUE THREAD

**Issue by rob-herb** [sensu-plugins/sensu-plugins-docker#44]
The current gemspec file has a dependency on Sensu Plugin up to 1.2.0 which was released in July 2015. Users such as myself are unable to make use of this Sensu docker plugin due to using more up-to-date-Sensu deployments. I am happy to open a PR which bumps the version dependency in the gemspec, but I am unsure as to the implications.

**Comment by psyhomb** [comment]
Is there any updates on this?

**Comment by betorvs** [comment]
+1

**Comment by eheydrick** [comment]
I have relaxed the dependency to `~> 1.2` and released the change in 1.1.5, which is now live on Rubygems.
