### ISSUE TITLE
All docker engine api versions not supported

### ISSUE THREAD

**Issue by d4n13lbc** [sensu-plugins/sensu-plugins-docker#45]
In order to make it works I had to modify the following file:
https://github.com/sensu-plugins/sensu-plugins-docker/blob/master/bin/check-container.rb

In the following way:
`
container_state = JSON.parse(response.body)['State']['Status'] 
`
to:
`
container_running = JSON.parse(response.body)['State']['Running'] 
`

container_running is a boolean variable so the conditional expression also change:

`
if container_running 
`

**Comment by majormoses** [comment]
@d4n13lbc would you be willing to put togeter a PR?
