### ISSUE TITLE
New release planned ?

### ISSUE THREAD

**Issue by obazoud** [sensu-plugins/sensu-plugins-docker#49]
Is a new release planned ?
(with this commit e9c47e12b11a711d0991b70b53a356a6c1f6bad5)

**Comment by eheydrick** [comment]
Hey @obazoud. New release out soon.

**Comment by eheydrick** [comment]
1.2.0 is live on rubygems.

**Comment by obazoud** [comment]
![](https://media4.giphy.com/media/vCKC987OpQAco/200_s.gif)

Thanks @eheydrick !
