### ISSUE TITLE
need to add sys-proctable as a dependency package

### ISSUE THREAD

**Issue by oba11** [sensu-plugins/sensu-plugins-docker#6]
[metrics-docker-container.rb](https://github.com/sensu-plugins/sensu-plugins-docker/blob/master/bin/metrics-docker-container.rb) fail if not manually installed

**Comment by mattyjones** [comment]
@oba11  Would you like to submit a PR for this and I will merge it in.

Thanks!

**Comment by oba11** [comment]
Hi @mattyjones, I v opened the PR here https://github.com/sensu-plugins/sensu-plugins-docker/pull/7.
Thank you.
