### ISSUE TITLE
error getting assets for event: TypeError: Cannot access member 'split' of undefined

### ISSUE THREAD

**Issue by maitza** [sensu-plugins/sensu-plugins-docker#86]
Hi,

When I'm trying to start check I'm getting following error:

`error getting assets for event: TypeError: Cannot access member 'split' of undefined`

Any idea? Asset looks installed correctly.

**Comment by nixwiz** [comment]
Answered in the Sensu Community Slack.  The asset definitions in the .bonsai.yaml need to change from
```   - entity.system.platform_release.split('.')[0]```
to
```   - entity.system.platform_version.split('.')[0]```
